version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    # - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.203 #optional
    volumes:
      #- /home/gizet/jellyfin/config:/config #on the right side is on the container and left-side is on the sharedrive
      - /mnt/devlab-share/00 Infra/Jellyfin/config:/config #
      - /mnt/devlab-share/00 Infra/Jellyfin/cache:/cache #
      - /mnt/devlab-share/05 Media/03 Movies:/data/movies #
      - /mnt/devlab-share/05 Media/04 TV Shows:/data/tvshows #
      - /mnt/devlab-share/05 Media/05 Music:/data/music #
      - /mnt/devlab-share/05 Media/06 Level UP:/data/levelup #
      - /mnt/devlab-share/05 Media/07 Photos:/data/photos #
      - /mnt/devlab-share/05 Media/08 Shorts:/data/shorts #
      - /mnt/devlab-share/05 Media/09 Dji:/data/dji #

    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped