version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    # - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.203 #optional
    volumes:
      #- /mnt/devlab-share/jellyfin/conf:/config #right side inside the container
      #- /home/gizet/jellyfin/config:/config
      - /mnt/devlab-share/jellyfin/media/configuration:/config:ro #
      - /mnt/devlab-share/jellyfin/cache:/cache #
      - /mnt/devlab-share/jellyfin/media/tvshows:/data/tvshows #
      - /mnt/devlab-share/jellyfin/media/movies:/data/movies #
      - /mnt/devlab-share/jellyfin/media/shorts:/data/shorts #
      - /mnt/devlab-share/jellyfin/media/photos:/data/photos #
      - /mnt/devlab-share/jellyfin/media/music:/data/music #
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
